- name: Add proxy
  hosts: GALA_MikroTik_FRN
  gather_facts: false
  connection: network_cli

  vars:
    ansible_command_timeout: 180

  tasks:
    - name: Edit address list Proxy
      routeros_command:
        commands:
          - /ip proxy set anonymous=yes cache-path=web-proxy1 enabled=yes parent-proxy=0.0.0.0 port=3128
          - /ip firewall address-list remove [/ip firewall address-list find address=("109.197.26.101")]
          - /ip firewall address-list add address=("46.22.56.21") list=Proxy
