- name: firewall_KEYMARC_KKT
  hosts: GALA_MikroTik_MPR
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Addreslist_FIREWALL
      routeros_command:
        commands:
        - /ip firewall address-list add address=prod01.okp-fn.ru list=KEYMARC_KKT
        - /ip firewall filter add action=accept chain=forward comment=KEYMARC_KKT dst-address-list=KEYMARC_KKT out-interface-list=WAN place-before=[/ip firewall filter find chain=forward comment="VTBnew"]