- name: Add WAN Onegin addr list
  hosts: GALA_MikroTik_MPR, GALA_MikroTik_FRN
  gather_facts: false
  connection: network_cli

  vars:
    ansible_command_timeout: 180

  tasks:
    - name: Edit address list
      routeros_command:
        commands:
          - :if ([:len [/ip firewall address-list find list=InetAdmin]] > 0) do={/ip firewall address-list add address=("85.235.52.188") list=InetAdmin}
          - :if ([:len [/ip firewall address-list find list=Admin]] > 0) do={/ip firewall address-list add address=("85.235.52.188") list=Admin}
          - /ip service set address="" [find name="winbox"]
