- name: Allow AnyDesk on MPR
  hosts: GALA_MikroTik_MPR
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Edit address list InternetServers
      routeros_command:
        commands:
          - :if ([:len [/ip fire address-list find list="InternetServers"]] > 0) do={:put [/ip firewall address-list add list="InternetServers" address="relays.net.anydesk.com"]}
