- name: backup
  hosts: GALA_MikroTik_MPR
  gather_facts: false
  connection: network_cli
  vars:
    ansible_command_timeout: 180
    backup_file: "{{ ansible_ssh_host }}.backup"
  tasks:
    - name: export config
      routeros_facts:
        gather_subset: config
    - name: save output
      local_action: copy content={{ ansible_net_config }} dest=/var/lib/awx/projects/mikrotik/MRP/{{ backup_file }}
    - name: zip catalog
      local_action: archive path=/var/lib/awx/projects/mikrotik/MRP dest=/var/lib/awx/projects/backup/MPR_{{lookup('pipe','date \"+%Y-%m-%d\"')}}.zip format=zip
      run_once: true
    - name: find old zip
      local_action: find paths=/var/lib/awx/projects/backup/ age=8w patterns="MPR_*.zip"
      register: collected_files
      run_once: true
    - name: del old zip
      local_action: file path="{{ item.path }}" state=absent
      with_items: "{{ collected_files.files }}"
      run_once: true
