- name: backup
  hosts: BF
  gather_facts: false
  connection: network_cli
  vars:
<<<<<<< HEAD
    backup_file: "{{ ansible_ssh_host }}-{{ ansible_date_time.date }}.backup"
=======
    backup_file: "{{ name }}-{{ ansible_date_time.date }}.backup"
>>>>>>> ebb26838837b3a3b021793c8b62f1ff638761bdd
  tasks:
    - name: export config
      routeros_command:
        commands:
          - /system backup save dont-encrypt=yes name="{{ backup_file }}"
    - name: get file
      net_get:
        src: "{{ backup_file }}"
        dest : "/var/lib/awx/projects/mikrotik/{{ backup_file }}"