---

- name: Change admin password MikroTik
  hosts: GALA_MikroTik_MPR
  gather_facts: false
  connection: network_cli

  vars:
    adm_password:

  tasks:
    - name: Change password
      routeros_command:
        commands:
          - /user set [find name=admin] password={{ adm_password }}
