---

- name: Change admin password MikroTik MPR
  hosts: newshop
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Set shop name
      routeros_command:
        commands:
          - /system identity set name="test"
    - name: Note
      debug:
        msg:
          - "{{ adm_password }}"
