---

- name: Change admin password MikroTik MPR
  hosts: GALA_MikroTik_MPR
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Change password
      routeros_command:
        commands:
          - /user set [find name={{ adm_username }}] password={{ adm_password }}
      no_log: true
