---

- name: Change admin password MikroTik
  hosts: BF
  gather_facts: false
  connection: network_cli

  vars_files:
    - 'vault_password.yml'

  tasks:
    - name: Change password
      routeros_command:
        commands:
          - /user set [find name=admin] password={{ adm_password }}
