- name: Change IP address for MPR (FRN 248, MPR 242)
  hosts: newshop
  gather_facts: false
  connection: network_cli

  vars:
    ansible_command_timeout: 180
    octet_3rd: "{{ ansible_ssh_host | regex_search('[0-9]+(?=\\.[0-9]+$)') }}"

  tasks:
    - name: Note!
      debug:
        msg:
          - "{{ octet_3rd }}"

    - name: Set IP adresses
      routeros_command:
        commands:
          #- /ip address add address=("10.242."."{{ octet_3rd }}".".62/26") interface=VLAN10
          - /ip address add address=("10.242."."{{ octet_3rd }}".".126/26") interface=VLAN40
          #- /ip address add address=("10.242."."{{ octet_3rd }}".".190/26") interface=VLAN30
          #- /ip address add address=("10.242."."{{ octet_3rd }}".".254/26") interface=VLAN20
