- name: Create BGP peers on EKB VPN-hub
  hosts: MT CHR Малышева
  gather_facts: false
  connection: network_cli

  vars:
    ansible_command_timeout: 180
    mpr_code:

  tasks:
    - name: Create BGP peers
      routeros_command:
        commands:
          - /routing bgp peer add hold-time=30s in-filter=vpn-bgp-in name=("MPR_"."{{mpr_code}}") out-filter=vpn-bgp-out remote-address=("10.193.242."."{{mpr_code}}") remote-as=65000 route-reflect=yes ttl=default
