- name: Get ISP1 addresses
  hosts: 10.241.130.254,10.241.121.254
  gather_facts: false
  connection: network_cli

  vars:
    ansible_command_timeout: 180
    addr:

  tasks:
    - name: Get address
      routeros_command:
        commands:
          - /ip address print where interface="ether1-ISP1"
      register: addr

    - name: print addr
      ansible.builtin.debug:
        var: addr

    - copy:
        content: "{{ addr.stdout }}"
        dest: "/home/output.txt"
