- name: Remove All Netwatch rules
  hosts: GALA_MikroTik_FRN
  gather_facts: false
  connection: network_cli
  vars:
    ansible_command_timeout: 180
  tasks:
    - name: remove old netwatch rules
      routeros_command:
        commands: /tool netwatch remove [find]