- name: Remove old tunnels FRN
  hosts: GALA_MikroTik_FRN
  gather_facts: false
  connection: network_cli

  vars:
    ansible_command_timeout: 180

  tasks:
    - name: Remove old tunnels
      routeros_command:
        commands:
          - /routing ospf interface remove [find interface=FRN_CO]
          - /routing ospf interface remove [find interface=FRN_DC]
          - /routing ospf network remove [find network="10.166.250.0/24"]
          - /routing ospf network remove [find network="10.166.253.0/24"]
          - /interface list member remove [find interface=FRN_CO]
          - /interface list member remove [find interface=FRN_DC]
          - /ip firewall address-list remove [find list=VPN-CO]
          - /ip firewall address-list remove [find list=VPN-DC]
          - /interface l2tp-client remove [find name=FRN_CO]
          - /interface l2tp-client remove [find name=FRN_DC]
          - /ip route remove [find dst-address="195.58.22.249/32"]
          - /ip route remove [find dst-address="195.151.219.233/32"]
