- name: Remove address-list Promsvyazvank from BF
  hosts: GALA_MikroTik_BF
  gather_facts: false
  connection: network_cli

  vars:
    ansible_command_timeout: 180

  tasks:
    - name: Remove address-list Promsvyazvank from BF
      routeros_command:
        commands:
          - /ip firewall address-list remove [find list="Promsvyazbank"]
