- name: Add proxy
  hosts: GALA_MikroTik_MPR
  gather_facts: false
  connection: network_cli

  vars:
    ansible_command_timeout: 180

  tasks:
    - name: Reset counters
      routeros_command:
        commands:
          - /ip firewall filter reset-counters [find dst-port="3128"]
