- name: firewall
  hosts: 192.167.170.254
  gather_facts: false
  connection: network_cli
  tasks:
    - name: check-for-updates
      routeros_command:
        commands:
          - /system package update set chanel=stable