- name: update
  hosts: BF
  gather_facts: false
  connection: network_cli
  tasks:
    - name: check-for-updates
      routeros_command:
        commands:
          - /system package update set chanel=stable
          - /system package update install