- name: update router os Firmware and hardware
  hosts: BF
  gather_facts: false
  connection: network_cli
  tasks:
    - name: START
      debug:
        msg: "-------START UPDATE PROCEDURE-------"
    - name: check-version-routerboard
      routeros_command:
        commands: /system routerboard print
      register: system_routerboard_print
    - name: Print routerboard version hardvare
      debug:
        var: system_print.stdout_lines[0][1]