- name: DHCP server new DNS
  hosts: GALA_MikroTik_OFC
  gather_facts: false
  connection: network_cli
  vars:
    ansible_command_timeout: 180
  tasks:
    - name: set DHCP network DNS
      routeros_command:
        commands:
          - /ip dhcp-server network set [ find dns-server~"192\\.168\\.49\\.1" ] dns-server=10.193.48.48,10.192.51.41
          - /ip dhcp-server network set [ find dns-server~"192\\.168\\.12\\.7" ] dns-server=10.193.48.48,10.192.51.41