- name: Change OFD Firewall rule
  hosts: GALA_MikroTik_MPR
  gather_facts: false
  connection: network_cli
  vars:
    ansible_command_timeout: 180
  tasks:
    - name: Change rule
      routeros_command:
        commands:
          - / ip firewall filter set [find comment=OFD] dst-port=21101,21102,7777,7778,5000,4000