- name: New DNS for MPR
  hosts: GALA_MikroTik_MPR
  gather_facts: false
  connection: network_cli
  vars:
    ansible_command_timeout: 180
  tasks:
    - name: Change DNS client
      routeros_command:
        commands:
          #- /ip dns set servers=10.193.48.48,10.192.51.41
          - /ip dns cache flush
