- name: SWITCH VLAN
  hosts: all
  gather_facts: false
  connection: local
  vars:
    getpass:
  tasks:
    - name: set VLAN10 to 21 port
      telnet:
        user: admin
        password: "{{getpass}}"
        login_prompt: "UserName: "
        prompts:
          - "[>|#]"
        command:
          - config vlan default delete 21
          - config vlan Data add untagged 21
          - save