- name: SWITCH VLAN
  hosts: onedlink
  gather_facts: false
  connectionon: network_cli
  tasks:
    - name: VLAN default port DELETED
      telnet:
        user: admin
        password: Crkthjp2
        login_prompt: "Username: "
        prompts:
          - "[>|#]"
        command:
          - config vlan default delete 21
          - config vlan Data add untagged 21
          - save